/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ArbolBinario;

/**
 *
 * @author SebasCarlosama
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panel_informacion_persona = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_numero_cedula = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_codigo_provincia = new javax.swing.JTextField();
        txt_codigo_canton = new javax.swing.JTextField();
        txt_codigo_parroquia = new javax.swing.JTextField();
        txt_fecha_nacimiento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_respuesta = new javax.swing.JTextArea();
        btn_ingresar = new javax.swing.JButton();
        btn_preOrder = new javax.swing.JButton();
        btn_inOrder = new javax.swing.JButton();
        btn_postOrder = new javax.swing.JButton();
        txt_buscar_cedula = new javax.swing.JTextField();
        btn_buscar_cedula = new javax.swing.JButton();
        btn_tamanio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Árbol Binario de Busqueda");

        jLabel2.setText("Realizado por: Erick Sebastian Carlosama Tabango.");

        jLabel3.setText("Información Persona");

        jLabel4.setText("Número de cédula:");

        jLabel5.setText("Nombre:");

        jLabel6.setText("Apellido:");

        jLabel7.setText("Código provincia:");

        jLabel8.setText("Código cantón:");

        jLabel9.setText("Código parroquia:");

        jLabel10.setText("Fecha Nacimiento:");

        txt_numero_cedula.setText("500");

        txt_nombre.setText("Sebas");

        txt_apellido.setText("Carlosama");

        txt_codigo_provincia.setText("10");

        txt_codigo_canton.setText("10");

        txt_codigo_parroquia.setText("10");

        txt_fecha_nacimiento.setText("21/12/1998");

        javax.swing.GroupLayout panel_informacion_personaLayout = new javax.swing.GroupLayout(panel_informacion_persona);
        panel_informacion_persona.setLayout(panel_informacion_personaLayout);
        panel_informacion_personaLayout.setHorizontalGroup(
            panel_informacion_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_informacion_personaLayout.createSequentialGroup()
                .addGroup(panel_informacion_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_informacion_personaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_informacion_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(31, 31, 31)
                        .addGroup(panel_informacion_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_fecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_codigo_parroquia, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_codigo_canton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_codigo_provincia, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_numero_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_informacion_personaLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel3)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panel_informacion_personaLayout.setVerticalGroup(
            panel_informacion_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_informacion_personaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(panel_informacion_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_informacion_personaLayout.createSequentialGroup()
                        .addGroup(panel_informacion_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_informacion_personaLayout.createSequentialGroup()
                                .addGroup(panel_informacion_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_informacion_personaLayout.createSequentialGroup()
                                        .addGroup(panel_informacion_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(panel_informacion_personaLayout.createSequentialGroup()
                                                .addGroup(panel_informacion_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(panel_informacion_personaLayout.createSequentialGroup()
                                                        .addGroup(panel_informacion_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel4)
                                                            .addComponent(txt_numero_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel5))
                                                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel6))
                                            .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7))
                                    .addComponent(txt_codigo_provincia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addComponent(txt_codigo_canton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 24, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(panel_informacion_personaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_codigo_parroquia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_informacion_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(txt_fecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        txt_respuesta.setColumns(20);
        txt_respuesta.setRows(5);
        jScrollPane1.setViewportView(txt_respuesta);

        btn_ingresar.setText("Ingresar");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });

        btn_preOrder.setText("PreOrder");
        btn_preOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_preOrderActionPerformed(evt);
            }
        });

        btn_inOrder.setText("InOrder");
        btn_inOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inOrderActionPerformed(evt);
            }
        });

        btn_postOrder.setText("PostOrder");
        btn_postOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_postOrderActionPerformed(evt);
            }
        });

        txt_buscar_cedula.setText("650");

        btn_buscar_cedula.setText("Buscar");
        btn_buscar_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_cedulaActionPerformed(evt);
            }
        });

        btn_tamanio.setText("Tamaño");
        btn_tamanio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tamanioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(194, 194, 194))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(panel_informacion_persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(txt_buscar_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_tamanio)
                                    .addComponent(btn_buscar_cedula)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btn_ingresar)
                        .addGap(258, 258, 258)
                        .addComponent(btn_preOrder)
                        .addGap(18, 18, 18)
                        .addComponent(btn_inOrder)
                        .addGap(18, 18, 18)
                        .addComponent(btn_postOrder)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(panel_informacion_persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(txt_buscar_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscar_cedula)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ingresar)
                    .addComponent(btn_preOrder)
                    .addComponent(btn_inOrder)
                    .addComponent(btn_postOrder)
                    .addComponent(btn_tamanio))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ArbolBinarioDeBusqueda arbol;
    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        try {
            String numero_cedula = txt_numero_cedula.getText();
            String nombre = txt_nombre.getText();
            String apellido=txt_apellido.getText();
            int cod_provincia=Integer.parseInt(txt_codigo_provincia.getText());
            int cod_canton=Integer.parseInt(txt_codigo_canton.getText());
            int cod_parroquia=Integer.parseInt(txt_codigo_parroquia.getText());
            String fecha = txt_fecha_nacimiento.getText();
            Persona persona = new Persona(numero_cedula, nombre, apellido, cod_provincia, cod_canton, cod_parroquia, fecha);
            
            if(arbol==null) {arbol = new ArbolBinarioDeBusqueda();}
            
            arbol.Ingresar(persona);
            txt_respuesta.setText(arbol.Ingresar(persona)+"\n"+persona.toString());
                    
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_preOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_preOrderActionPerformed
        NodoArbolBinario nodo = arbol.getRaiz();
        txt_respuesta.setText(arbol.PreOrder(nodo));
    }//GEN-LAST:event_btn_preOrderActionPerformed

    private void btn_inOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inOrderActionPerformed

        txt_respuesta.setText(arbol.InOrder(arbol.getRaiz()));
    }//GEN-LAST:event_btn_inOrderActionPerformed

    private void btn_postOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_postOrderActionPerformed
        txt_respuesta.setText(arbol.PostOrder(arbol.getRaiz()));
    }//GEN-LAST:event_btn_postOrderActionPerformed

    private void btn_buscar_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_cedulaActionPerformed
        txt_respuesta.setText(arbol.BuscarCedula(txt_buscar_cedula.getText(), arbol));
    }//GEN-LAST:event_btn_buscar_cedulaActionPerformed

    private void btn_tamanioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tamanioActionPerformed
        if (arbol==null) {
            txt_respuesta.setText("0");
        }else{
        txt_respuesta.setText(""+arbol.TamnioArbol(arbol.getRaiz()));
        }
    }//GEN-LAST:event_btn_tamanioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar_cedula;
    private javax.swing.JButton btn_inOrder;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_postOrder;
    private javax.swing.JButton btn_preOrder;
    private javax.swing.JButton btn_tamanio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_informacion_persona;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_buscar_cedula;
    private javax.swing.JTextField txt_codigo_canton;
    private javax.swing.JTextField txt_codigo_parroquia;
    private javax.swing.JTextField txt_codigo_provincia;
    private javax.swing.JTextField txt_fecha_nacimiento;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_numero_cedula;
    private javax.swing.JTextArea txt_respuesta;
    // End of variables declaration//GEN-END:variables
}
